In [21]:
from sklearn.mixture import GaussianMixture
import torch
from synth_data_samples import get_synth_data_sample

In [8]:
data_set = 1
archetypes, X, Strue, size, alpha = get_synth_data_sample(data_set)

In [14]:
gm = GaussianMixture(n_components=3, covariance_type='full', max_iter=100,tol=1e-5, init_params='random')
gm.fit(X)


GaussianMixture(init_params='random', n_components=3, tol=1e-05)

In [22]:
torch.tensor(gm.means_)

tensor([[0.2738, 0.2755, 0.8775],
        [0.8384, 0.3176, 0.3167],
        [0.2481, 0.8609, 0.3352]], dtype=torch.float64)

In [16]:
gm.weights_

array([0.32356087, 0.34293884, 0.33350029])

In [17]:
gm.covariances_

array([[[ 0.03617366, -0.00241942, -0.01237998],
        [-0.00241942,  0.03425064, -0.01036378],
        [-0.01237998, -0.01036378,  0.00873514]],

       [[ 0.01200968, -0.01399613, -0.01287134],
        [-0.01399613,  0.04261453, -0.00856743],
        [-0.01287134, -0.00856743,  0.0412667 ]],

       [[ 0.02945399, -0.00751633, -0.00480416],
        [-0.00751633,  0.01076891, -0.01731967],
        [-0.00480416, -0.01731967,  0.04471406]]])

In [18]:
gm.lower_bound_

1.4293978975182267

In [19]:
gm.converged_

True

In [20]:
gm.n_iter_

24